SmashSite/Annotation/urls.py
from django.conf.urls import url, include
from django.views.generic import ListView
from Annotation.models import Vod, Post
from . import views

urlpatterns = [
    url(r'^page(?P<page>[0-9]+)$', views.vod, name="Annotation-feed"),
    url(r'^(?P<key>[0-9]+)$', views.post, name="Annotation-post"),
    url(r'^vote(?P<vkey>[0-9]+)/(?P<key>[0-9]+)$', views.vote, name="Annotation-vote"),
    url(r'^delete(?P<vkey>[0-9]+)/(?P<key>[0-9]+)$', views.delete, name="Annotation-delete"),    
    url(r'^deleteVod(?P<vkey>[0-9]+)', views.delete_vod, name="Annotation-delete-vod"),
    url(r'^Search(?P<search_text>.*)', views.search, name="Annotation-search")
    ]

SmashSite/Profile/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^(?P<key>[0-9]+)$', views.profile, name="profile"),
]

SmashSite/SmashSite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from SmashSite import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^register$', views.register, name='register'),
    url(r'^login_user$', views.login_user, name='login_user'),
    url(r'^Annotation', include('Annotation.urls')),
    url(r'^Profile', include('Profile.urls')),
    url(r'^logout', views.user_logout, name='logout_user')
]

SmashSite/Annotation/models.py
from django.db import models
from django.contrib.auth.models import User
from vote.managers import VotableManager
from django.utils import timezone
import math

class Post(models.Model):
    user = models.ForeignKey(User, default=0)
    body = models.TextField()
    time = models.IntegerField(default=0)
    date = models.DateTimeField(default=timezone.now)
    votes = VotableManager()
    vote_count = models.IntegerField(default=0)

    #convert the seconds given by youtupe api to more readable format for ux
    def formatTime(self):
        seconds_value = self.time % 60
        seconds = str(seconds_value)
        if seconds_value < 10:
            seconds = "0" + str(seconds_value)
        minutes = math.floor(self.time/60)
        return "{}:{}".format(str(minutes),seconds)

    def __str__(self):
        return self.user.username + str(self.pk)

class Vod(models.Model):
    user = models.ForeignKey(User, default=0)
    url = models.URLField(default='')
    title = models.CharField(max_length=30)
    date = models.DateTimeField(default=timezone.now)
    posts = models.ManyToManyField(Post)
    #tags = models.TextField(max_length=100, default='')

    #used to parse youtube id from urls given by users, used in
    #thumbnail generation and various other operations
    #pre-condition: just normal youtube link, not embed
    def return_youtube_id(self):
        return self.url[-11:]
    
    def __str__(self):
        return self.user.username + str(self.pk)

SmashSite/Annotation/forms.py
from Annotation.models import Post, Vod
from django import forms
from captcha.fields import ReCaptchaField

class PostForm(forms.ModelForm):
    body = forms.CharField(widget=forms.Textarea)
    time = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    captcha = ReCaptchaField()
    
    class Meta:
        model = Post
        fields = ['body', 'time', 'captcha']

    def __str__(self):
        return self.user.username

class VodForm(forms.ModelForm):
    title = forms.CharField()
    url = forms.URLField()
    captcha = ReCaptchaField()
    #tags = forms.CharField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Vod
        #fields = ['title', 'url', 'tags']
        fields = ['title', 'url', 'captcha']

    def __str__(self):
        return self.user.username

SmashSite/Annotation/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from Annotation.models import Vod, Post
from Annotation.forms import PostForm, VodForm
import datetime
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.urls import reverse
import math

def post(request, key):
    #retrieves the specific vod object
    try:
        target_vod = Vod.objects.get(pk=int(key))
    except Vod.DoesNotExist:
        raise Http404("Vod does not exist")

    #handles commenting
    if request.method == "POST" and 'comment' in request.POST:
        form = PostForm(request.POST)
        user = request.user
        if user is not None:
            if form.is_valid():
                current_post = form.save(commit=False)
                current_post.user = user
                current_post.save()
                target_vod.posts.add(current_post)
                return HttpResponseRedirect(reverse("Annotation-post",args=[key]))
            else:
                print(form.errors)

    #loads the form for input if not POST
    else:
        form = PostForm()

    #using vod object, retrieves all its posts and renders
    target_posts = Vod.objects.get(pk=int(key)).posts.all().order_by("-date")
    context = {'target_vod': target_vod, 'target_posts': target_posts, 'form':form}

    return render(request, 'Annotation/post.html', context)

def vod(request, page):
    #acquires 24 vods
    page = int(page)
    start = page * 24
    end = start + 24
    queryset = Vod.objects.all().order_by("-date")[start:end]


    if request.method == "POST":
        form = VodForm(request.POST)
        user = request.user
        if user is not None:
            if form.is_valid():
                current_vod = form.save(commit=False)
                current_vod.user = user
                current_vod.save()
                return HttpResponseRedirect(reverse("Annotation-feed", kwargs={'page':0}))
            else:
                print(form.errors)
    else:
        form = VodForm()

    #used to determine whether to display pages
    pages = Vod.objects.all().count()
    previous = False
    after = False
    if (page - 1) >= 0:
        previous = True
    if pages > (page + 1) * 24:
        after = True

    context = {'object_list':queryset, 'form':form, 'page':page, 'previous':previous, 'after':after}

    return render(request, 'Annotation/home.html', context)

def vote(request,vkey, key):
    user = request.user
    #retrieves specific post
    try:
        target_post = Post.objects.get(pk=int(key))
    except Post.DoesNotExist:
        raise Http404("Post does not exist")

    if user is not None:
        #user can only upvote or remove previous vote
        if target_post.votes.exists(user.id):
            target_post.votes.down(user.id)
        else:
            target_post.votes.up(user.id)
        target_post.vote_count = target_post.votes.count()
        target_post.save()

    return HttpResponse(target_post.vote_count)

def delete(request, vkey, key):
    user = request.user
    try:
        target_post = Post.objects.get(pk=int(key))
    except Post.DoesNotExist:
        raise Http404("Post does not exist")

    if user is not None:
        target_post.delete()

    return redirect(post, key=int(vkey))

def delete_vod(request, vkey):
    user = request.user
    try:
        target_vod = Vod.objects.get(pk=int(vkey))
    except Vod.DoesNotExist:
        raise Http404("Vod does not exist")

    if user is not None:
        all_posts = target_vod.posts.all()
        all_posts.delete()
        target_vod.delete()

    return redirect("Annotation-feed", page=0)

def search(request, search_text):
    search_vods = Vod.objects.filter(title__contains=search_text).order_by("-date")
    form = VodForm()
    context = {'object_list':search_vods, 'form':form}

    return render(request, 'Annotation/search.html', context)

SmashSite/Annotation/templates/Annotation/header.html
<!DOCTYPE html>
<html lang="en">

<head>
	<title>Smash Annotate</title>
	<meta charset="utf-8" />
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css"/>
	<link rel="stylesheet" href="{% static 'css/home_page.css' %}" type="text/css"/>
	<link rel="stylesheet" href="{% static 'css/extra_css.css' %}" type="text/css"/>
	<link rel="icon" type="image/png" href="{% static 'images/favicon-32x32.png' %}" sizes="32x32" />
	<link rel="icon" type="image/png" href="{% static 'images/favicon-16x16.png' %}" sizes="16x16" />

	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
	<div class="container-fluid">
		<nav class="navbar navbar-default">
			<div class="container-fluid">
				<div class="navbar-header">
      		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar-collapse" aria-expanded="false">
        		<span class="sr-only">Toggle navigation</span>
        		<span class="icon-bar"></span>
        		<span class="icon-bar"></span>
        		<span class="icon-bar"></span>
      		</button>
      		<a class="navbar-brand" href="Annotationpage0"><img src="{% static 'images/logo.png' %}"></a>
    		</div>
				<div class="collapse navbar-collapse" id="bs-navbar-collapse">
					<ul class="nav navbar-nav">
						{% if user.is_anonymous %}
							<li><a class="header-link" href="{% url 'login_user' %}">Login</a></li>
							<li><a class="header-link" href="{% url 'register' %}">Register</a></li>
						{% elif user.is_authenticated %}
							<li><a href="Profile{{ user.id }}">Profile</a></li>
							<li><a href="{% url 'logout_user' %}">Logout</a></li>
						{% endif %}
					</ul>
				</div>
			</div>
		</div>

		<!-- <div class="row panel">
			<ul class="nav navbar-nav">
				<li><a href="Annotationpage0"><img src="{% static 'images/logo.png' %}"></a></li>
				{% if user.is_anonymous %}
					<li><a class="header-link" href="{% url 'login_user' %}">Login</a></li>
					<li><a class="header-link" href="{% url 'register' %}">Register</a></li>
				{% elif user.is_authenticated %}
					<li><a href="Profile{{ user.id }}">Profile</a></li>
					<li><a href="{% url 'logout_user' %}">Logout</a></li>
				{% endif %}
			</ul>
		</div> -->








		<div class="container-fluid">
			{% block content %}
		  {% endblock %}
		</div>
	</div>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	{% load static %}
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>

</html>

SmashSite/Annotation/templates/Annotation/home.html
{% extends "Annotation/header.html" %}
{% load bootstrap %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/annotation_home.css' %}" type="text/css"/>

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			{% if user.is_authenticated %}
				<div class="col-md-3">
					<button type="button" class="btn btn-default" onclick="show()" id="showBtn">Post a game!</button>
				</div>
			{% endif %}
			<div id="search" class="col-md-3 pull-right">
				<div class="input-group">
					<input id="searchBox" type="text" class="form-control" placeholder="Search for...">
					<span class="input-group-btn">
						<button class="btn btn-default" onclick="search()">Go!</button>
					</span>
				</div>
			</div>
			<!-- Video submission form, not visible by defualt -->
			<div id="inputWell" class="well">
				<button type="button" class="btn btn-default" onclick="hide()" id="hideBtn">-</button>
				<form class="form-horizontal" action="{{ request.path }}" method="post" enctype="multipart/form-data">
					{% csrf_token %}

					<div class="form-group">
						{{ form.title|bootstrap_horizontal }}
					</div>
					<div class="form-group">
						{{ form.url|bootstrap_horizontal }}
					</div>
					<div class="form-group">
						<div class="col-sm-offset-2 col-sm-5">
							{{form.captcha}}

						</div>
						<div class="col-sm-2">
							<input type="submit" class="btn btn-primary" value="Post your game!"></button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>

	<div class="row">
	<!-- Lists vods -->
	{% for vod in object_list %}
		<div class="col-xs-6 col-md-3">
			<h2><a class="home-page" href="Annotation{{ vod.id }}">{{ vod.title }}</a></h2>
			<p>
				<a class="home-page" href="Profile{{ vod.user.id }}">{{vod.user.username}}</a> {{vod.date|timesince}} ago
				<!--a delete button if the poster is the current user-->
				{% if user.is_authenticated %}
					{% if user.id == vod.user.id or user.is_superuser %}
						<button type="button" class="btn btn-default btn-xs" id="delBtn" onClick="showDelete()">Delete</button>
						<a href="AnnotationdeleteVod{{vod.id}}" class="confirm home-page">yes</a>
						<a href="#" class="confirm home-page" onClick="hideDelete()">no</a>
					{% endif %}
				{% endif %}
			</p>
			<a href="Annotation{{ vod.id }}" class="thumbnail">
			  <img src="https://img.youtube.com/vi/{{ vod.return_youtube_id }}/mqdefault.jpg">
			</a>
		</div>
	{% endfor %}
	</div>

	<div class="row">
		<p style="text-align:center">
			{% if previous %}
				<a href="Annotationpage{{ page|add:'-1' }}">Prev</a>
			{% endif %}
			{% if after %}
				<a href="Annotationpage{{ page|add:1 }}">Next</a>
			{% endif %}
		</p>
	</div>
</div>
{% load staticfiles %}
<script src = "{% static 'js/characterselect.js' %}"></script>
<script src = "{% static 'js/homescript.js' %}"></script>
{% endblock %}

SmashSite/Annotation/templates/Annotation/post.html
{% extends "Annotation/header.html" %}

{% block content %}
<div class="container-fluid">
	<div class="col-md-12" style="width:100%;">
		<!--The youtube iframe-->
		<div class="col-md-8">
			<div id="ytplayer" class="embed-responsive embed-responsive-16by9">
				<iframe id="yt-player" src="https://www.youtube.com/embed/{{ target_vod.return_youtube_id }}?rel=0&enablejsapi=1" ></iframe>
			</div>
		</div>
		<div class="col-md-4">
			{% if user.is_authenticated %}
			<!--Comment Box-->
				<div class="row panel" id="comment-box">
					<div class="input-group">
						<form action="{{ request.path }}" method="post" enctype="multipart/form-data">
							{% csrf_token %}
							<div class="form-group" id="comment-form">
								<label for="comment">Comment</label>
								<textarea class="form-control" rows="8" cols="80" id="id_body" name="body"></textarea>
							</div>
							<div class="form-group">
								<div class="col-sm-7">
									{{ form.captcha }}
								</div>
								<div class="col-sm-2 col-sm-offset-1">
									<input type="submit" name="comment" class="btn btn-primary" onclick="logTime()" value="Post"></button>
								</div>
							</div>
							{{ form.time }}
						</form>
					</div>
				</div>
			{% endif %}
			<!--Comments, only display if there exists comments-->
			{% if target_posts %}
				<div class="panel" id="comment-pane">
				{% for post in target_posts %}
					<div class="post-box">
						<div class="row">
							<div class="row">
								<p>
									<button type="button" name="up" class="btn btn-default btn-xs" onclick="vote({{target_vod.id}}, {{post.id}})"><span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span></button>
									<a href="Profile{{ post.user.id }}">{{post.user.username}}</a> &nbsp;&nbsp; <span id="vote-count-{{post.id}}">{{post.vote_count}}</span> votes {{post.date|timesince}} ago
									<!--a delete button if the poster is the current user-->
									{% if user.is_authenticated %}
										{% if user.id == post.user.id  or user.is_superuser %}
											<button type="button" class="btn btn-default btn-xs" id="delBtn" onClick="showDelete()">Delete</button>
											<a href="Annotationdelete{{target_vod.id}}/{{ post.id }}" class="confirm">yes</a>
											<a href="#" class="confirm" onClick="hideDelete()">no</a>
										{% endif %}
									{% endif %}
								</p>
							</div>
							<div class="row">
								{{post.body|safe|linebreaks}}
							</div>
							<div class="row">
								<p>
									<a href="javascript:skipTo({{ post.time }})" class="time-control">{{ post.formatTime }}</a> | <a href="javascript:skipTo({{ post.time }}, true)" class="time-control">Half Speed</a>
								</p>
							</div>
						</div>
					</div>
				{% endfor %}
				</div>
			{% endif %}
		</div>
	</div>
</div>
{% load static %}
	<script src = "{% static 'js/postscript.js' %}"></script>
	<script>
		/**
		*Sends an ajax request, updating
		*/
		function vote(vodId, postId){
			url = "Annotationvote" + vodId + "/" + postId;
			$.ajax(url).done(function(data){
				$('#vote-count-' + postId).html(data);
			});
		}
	</script>
{% endblock %}

SmashSite/Annotation/templates/Annotation/search.html
{% extends "Annotation/header.html" %}
{% load bootstrap %}
{% block content %}
<div class="container-fluid">
	{% if object_list %}
		<div class="row">
		{% for vod in object_list %}
			<div class="col-xs-6 col-md-3">
				<h2 style="display:inline"><a href="Annotation{{ vod.id }}">{{ vod.title }}</a></h2>
				<p style="display:inline;">
					<a href="Profile{{ vod.user.id }}">{{vod.user.username}}</a> {{vod.date|timesince}} ago
					<!--a delete button if the poster is the current user-->
					{% if user.is_authenticated %}
						{% if user.id == vod.user.id %}
							<button type="button" class="btn btn-default btn-xs" id="delBtn" onClick="showDelete()">Delete</button>
							<a href="AnnotationdeleteVod{{vod.id}}" class="confirm">yes</a>
							<a href="#" class="confirm" onClick="hideDelete()">no</a>
						{% endif %}
					{% endif %}
				</p>
				<a href="Annotation{{ vod.id }}" class="thumbnail">
				  <img src="https://img.youtube.com/vi/{{ vod.return_youtube_id }}/mqdefault.jpg">
				</a>
			</div>
		{% endfor %}
		</div>
	{% else %}
		<h1 style="text-align:center;">No vods found!</h1>
	{% endif %}
</div>
{% endblock %}